apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: static-web1
  name: static-web1
spec:
  containers:
  - image: nginx
    name: static-web1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
