apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: obo-web
  name: obo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obo-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: obo-web
    spec:
      volumes:
      - name: web-config
        configMap:
          name: obo-web
      containers:
      - image: tantien3004/obo-web:1.5
        name: obo-web
        resources: {}
        command: ["sleep", "1000"]
          #command: ["java", "-Dspring.datasource.url=jdbc:mysql://10.0.2.15:3306/obo", "-jar", "target/obo-0.0.1-SNAPSHOT.jar"]
        volumeMounts:
        - name: web-config
          mountPath: /techmaster-obo-web/src/main/resources/application-dev.properties
          subPath: application-dev.properties
status: {}
